db_host = "127.0.0.1"
db_user = "root"
db_password = "123456"
db_database = "old"

bs_book_id = 78
bs_book_url = "https://mywiki.com/books/altes-wiki/page/"
bs_api_url = "https://mywiki.com/api/"
bs_token_id = "Somerandomid"
bs_token_secret = "Anothersuperrandomstring"